# Generated by Django 3.1.1 on 2020-09-28 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quicklink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicklink',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quicklink',
            name='image',
            field=models.ImageField(default='images/no_images.png', upload_to='images/%Y%m%d'),
        ),
        migrations.AddField(
            model_name='quicklink',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
