# Generated by Django 3.0.6 on 2020-05-28 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATCCode',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EDICode',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ICDCode',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OperationalDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd_subtract_days', models.IntegerField(blank=True, null=True)),
                ('icd_add_days', models.IntegerField(blank=True, null=True)),
                ('edi_subtract_days', models.IntegerField(blank=True, null=True)),
                ('edi_add_days', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('atc_code', models.ManyToManyField(related_name='atc_code', to='operationalDefinition.ATCCode')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operationalDefinition.Category')),
                ('edi_code', models.ManyToManyField(related_name='edi_code', to='operationalDefinition.EDICode')),
                ('icd_code', models.ManyToManyField(related_name='icd_code', to='operationalDefinition.ICDCode')),
                ('primary_icd_code', models.ManyToManyField(related_name='primary_icd_code', to='operationalDefinition.ICDCode')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
