# Generated by Django 3.0.6 on 2020-05-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationalDefinition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationaldefinition',
            name='atc_code',
            field=models.ManyToManyField(blank=True, null=True, related_name='atc_code', to='operationalDefinition.ATCCode'),
        ),
        migrations.AlterField(
            model_name='operationaldefinition',
            name='edi_code',
            field=models.ManyToManyField(blank=True, null=True, related_name='edi_code', to='operationalDefinition.EDICode'),
        ),
        migrations.AlterField(
            model_name='operationaldefinition',
            name='icd_code',
            field=models.ManyToManyField(blank=True, null=True, related_name='icd_code', to='operationalDefinition.ICDCode'),
        ),
    ]
