export {default as Home} from './Home'
export {default as About} from './About'
export {default as Solutions } from './Solutions'
export {default as Services } from './Services'
export {default as Support } from './Support'